#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrushPlane

#include "Basic.hpp"

#include "BP_BrushPlane_classes.hpp"
#include "BP_BrushPlane_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BrushPlane.BP_BrushPlane_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BrushPlane_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BrushPlane_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BrushPlane.BP_BrushPlane_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BrushPlane_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BrushPlane_C", "ReceiveTick");

	Params::BP_BrushPlane_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
