#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EmoteData_cLeon_26

#include "Basic.hpp"

#include "BP_EmoteData_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EmoteData_cLeon_26.BP_EmoteData_cLeon_26_C
// 0x0000 (0x02C8 - 0x02C8)
class ABP_EmoteData_cLeon_26_C final : public ABP_EmoteData_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EmoteData_cLeon_26_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EmoteData_cLeon_26_C")
	}
	static class ABP_EmoteData_cLeon_26_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EmoteData_cLeon_26_C>();
	}
};
DUMPER7_ASSERTS_ABP_EmoteData_cLeon_26_C;

SDK_NAMESPACE_END
