#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonCharacter_cLeon_Character_Survivor

#include "Basic.hpp"

#include "BP_FirstPersonCharacter_cLeon_Character_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FirstPersonCharacter_cLeon_Character_Survivor.BP_FirstPersonCharacter_cLeon_Character_Survivor_C
// 0x0030 (0x0D40 - 0x0D10)
class ABP_FirstPersonCharacter_cLeon_Character_Survivor_C : public ABP_FirstPersonCharacter_cLeon_Character_C
{
public:
	uint8                                         Pad_D10[0x8];                                      // 0x0D10(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        FilledValue;                                       // 0x0D18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PreStencil;                                        // 0x0D20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D24[0x4];                                      // 0x0D24(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UCapsuleComponent*>              OverlapCheckCapsules;                              // 0x0D28(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UClass*                                 HunterClass;                                       // 0x0D38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void SetStencilValue_Server_(int32 StencilValue);
	void ReceiveBeginPlay();
	void OverlapCheck();
	void ReceiveTick(float DeltaSeconds);
	void PlayerControllerSetup();
	void IsOverlap(int32* OverlapCountRezult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FirstPersonCharacter_cLeon_Character_Survivor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FirstPersonCharacter_cLeon_Character_Survivor_C")
	}
	static class ABP_FirstPersonCharacter_cLeon_Character_Survivor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FirstPersonCharacter_cLeon_Character_Survivor_C>();
	}
};
DUMPER7_ASSERTS_ABP_FirstPersonCharacter_cLeon_Character_Survivor_C;

SDK_NAMESPACE_END
