#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_WidgetUtility

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_WidgetUtility.BPI_WidgetUtility_C.GetRootFocusTarget
// 0x0008 (0x0008 - 0x0000)
struct BPI_WidgetUtility_C_GetRootFocusTarget final
{
public:
	class UWidget*                                Widget;                                            // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_WidgetUtility_C_GetRootFocusTarget;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
