#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_WidgetUtility

#include "Basic.hpp"

#include "BPI_WidgetUtility_classes.hpp"
#include "BPI_WidgetUtility_parameters.hpp"


SDK_NAMESPACE_START

// Function BPI_WidgetUtility.BPI_WidgetUtility_C.GetRootFocusTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void IBPI_WidgetUtility_C::GetRootFocusTarget(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_WidgetUtility_C", "GetRootFocusTarget");

	Params::BPI_WidgetUtility_C_GetRootFocusTarget Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


SDK_NAMESPACE_END
