#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_WidgetUtility

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_WidgetUtility.BPI_WidgetUtility_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_WidgetUtility_C final
{
public:
	void GetRootFocusTarget(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_WidgetUtility_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_WidgetUtility_C")
	}
	static class IBPI_WidgetUtility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_WidgetUtility_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_WidgetUtility_C;

SDK_NAMESPACE_END
