#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cLeon_game

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass cLeon_game.cLeon_game_C
// 0x0008 (0x02B8 - 0x02B0)
class AcLeon_game_C final : public ALevelScriptActor
{
public:
	uint8                                         Pad_2B0[0x8];                                      // 0x02B0(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("cLeon_game_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"cLeon_game_C")
	}
	static class AcLeon_game_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AcLeon_game_C>();
	}
};
DUMPER7_ASSERTS_AcLeon_game_C;

SDK_NAMESPACE_END
