#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CR_PaintMan_SimpleOffset

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


SDK_NAMESPACE_START

// RigVMBlueprintGeneratedClass CR_PaintMan_SimpleOffset.CR_PaintMan_SimpleOffset_C
// 0x0030 (0x0BA0 - 0x0B70)
class UCR_PaintMan_SimpleOffset_C final : public UControlRig
{
public:
	double                                        ZOffset_L_Target;                                  // 0x0B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZOffset_R_Target;                                  // 0x0B78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZOffset_R;                                         // 0x0B80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZOffset_L;                                         // 0x0B88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ZOffset_Pelvis;                                    // 0x0B90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldDoIKTrace;                                   // 0x0B98(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CR_PaintMan_SimpleOffset_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CR_PaintMan_SimpleOffset_C")
	}
	static class UCR_PaintMan_SimpleOffset_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCR_PaintMan_SimpleOffset_C>();
	}
};
DUMPER7_ASSERTS_UCR_PaintMan_SimpleOffset_C;

SDK_NAMESPACE_END
