#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_ItemCoreDataArray

#include "Basic.hpp"

#include "ST_ItemCoreDatas_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_ItemCoreDataArray.ST_ItemCoreDataArray
// 0x0018 (0x0018 - 0x0000)
struct FST_ItemCoreDataArray final
{
public:
	class FName                                   CustomName_7_ED217BBE4CD0010445A33DA59101C810;     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FST_ItemCoreDatas>              ItemCoreDatas_3_BFA3DF4D48E84650E96D99B0DEB64961;  // 0x0008(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FST_ItemCoreDataArray;

SDK_NAMESPACE_END
