#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_config

#include "Basic.hpp"

#include "UI_config_classes.hpp"


SDK_NAMESPACE_START

// Function UI_config.UI_config_C.Show Config
// (BlueprintCallable, BlueprintEvent)

void UUI_config_C::Show_Config()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_config_C", "Show Config");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
