#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_KeyImageCombo

#include "Basic.hpp"

#include "WBP_KeyImageCombo_classes.hpp"
#include "WBP_KeyImageCombo_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_KeyImageCombo.WBP_KeyImageCombo_C.UpdateInputDeviceAll
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EInputType                              InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_KeyImageCombo_C::UpdateInputDeviceAll(EInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeyImageCombo_C", "UpdateInputDeviceAll");

	Params::WBP_KeyImageCombo_C_UpdateInputDeviceAll Parms{};

	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_KeyImageCombo.WBP_KeyImageCombo_C.SetUpInputIcon
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FST_KeyImageComboBase>&   Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// class UPanelWidget*                     Box                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_KeyImageCombo_C::SetUpInputIcon(TArray<struct FST_KeyImageComboBase>& Array, class UPanelWidget* Box)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeyImageCombo_C", "SetUpInputIcon");

	Params::WBP_KeyImageCombo_C_SetUpInputIcon Parms{};

	Parms.Array = std::move(Array);
	Parms.Box = Box;

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);
}


// Function WBP_KeyImageCombo.WBP_KeyImageCombo_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_KeyImageCombo_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_KeyImageCombo_C", "PreConstruct");

	Params::WBP_KeyImageCombo_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
