#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NumberOnlyInputTextBlock

#include "Basic.hpp"

#include "WBP_NumberOnlyInputTextBlock_classes.hpp"
#include "WBP_NumberOnlyInputTextBlock_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.SetEditableText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_NumberOnlyInputTextBlock_C::SetEditableText(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "SetEditableText");

	Params::WBP_NumberOnlyInputTextBlock_C_SetEditableText Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NumberOnlyInputTextBlock_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "PreConstruct");

	Params::WBP_NumberOnlyInputTextBlock_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.GetText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString*                          Text                                                   (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_NumberOnlyInputTextBlock_C::GetText(class FString* Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "GetText");

	Params::WBP_NumberOnlyInputTextBlock_C_GetText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Text != nullptr)
		*Text = std::move(Parms.Text);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_K2Node_ComponentBoundEvent_5_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_K2Node_ComponentBoundEvent_5_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_K2Node_ComponentBoundEvent_5_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_2_K2Node_ComponentBoundEvent_7_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_2_K2Node_ComponentBoundEvent_7_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_2_K2Node_ComponentBoundEvent_7_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_1_K2Node_ComponentBoundEvent_6_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_1_K2Node_ComponentBoundEvent_6_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_1_K2Node_ComponentBoundEvent_6_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature");

	Params::WBP_NumberOnlyInputTextBlock_C_BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_K2Node_ComponentBoundEvent_8_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_K2Node_ComponentBoundEvent_8_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_K2Node_ComponentBoundEvent_8_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_2_K2Node_ComponentBoundEvent_10_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_2_K2Node_ComponentBoundEvent_10_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_2_K2Node_ComponentBoundEvent_10_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_1_K2Node_ComponentBoundEvent_9_OnClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_NumberOnlyInputTextBlock_C::BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_1_K2Node_ComponentBoundEvent_9_OnClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_1_K2Node_ComponentBoundEvent_9_OnClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.AddNumber
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_NumberOnlyInputTextBlock_C::AddNumber(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_NumberOnlyInputTextBlock_C", "AddNumber");

	Params::WBP_NumberOnlyInputTextBlock_C_AddNumber Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
