#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NumberOnlyInputTextBlock

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C
// 0x0080 (0x03C0 - 0x0340)
class UWBP_NumberOnlyInputTextBlock_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_UpOrDownButton_C*                  WBP_Up_2;                                          // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UpOrDownButton_C*                  WBP_Up_1;                                          // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UpOrDownButton_C*                  WBP_Up;                                            // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_NavInputTextBlock_C*               WBP_NavInputTextBlock;                             // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UpOrDownButton_C*                  WBP_Down_2;                                        // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UpOrDownButton_C*                  WBP_Down_1;                                        // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UpOrDownButton_C*                  WBP_Down;                                          // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FIntVector2                            Number_Range;                                      // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max_Text_Length;                                   // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38C[0x4];                                      // 0x038C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Default_Text;                                      // 0x0390(0x0010)(Edit, BlueprintVisible)
	class FText                                   Empty_Default_Text;                                // 0x03A0(0x0010)(Edit, BlueprintVisible)
	TMulticastInlineDelegate<void(class FText Text)> TextChanged;                                    // 0x03B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void SetEditableText(const class FText& InText);
	void PreConstruct(bool IsDesignTime_PreConstruct);
	void GetText(class FString* Text);
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_K2Node_ComponentBoundEvent_5_OnClickedEvent__DelegateSignature();
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_2_K2Node_ComponentBoundEvent_7_OnClickedEvent__DelegateSignature();
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Up_1_K2Node_ComponentBoundEvent_6_OnClickedEvent__DelegateSignature();
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_K2Node_ComponentBoundEvent_8_OnClickedEvent__DelegateSignature();
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_2_K2Node_ComponentBoundEvent_10_OnClickedEvent__DelegateSignature();
	void BndEvt__WBP_NumberOnlyInputTextBlock_WBP_Down_1_K2Node_ComponentBoundEvent_9_OnClickedEvent__DelegateSignature();
	void AddNumber(int32 Value);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NumberOnlyInputTextBlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NumberOnlyInputTextBlock_C")
	}
	static class UWBP_NumberOnlyInputTextBlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NumberOnlyInputTextBlock_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NumberOnlyInputTextBlock_C;

SDK_NAMESPACE_END
