#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NumberOnlyInputTextBlock

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.SetEditableText
// 0x0010 (0x0010 - 0x0000)
struct WBP_NumberOnlyInputTextBlock_C_SetEditableText final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_NumberOnlyInputTextBlock_C_SetEditableText;

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_NumberOnlyInputTextBlock_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_NumberOnlyInputTextBlock_C_PreConstruct;

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.GetText
// 0x0020 (0x0020 - 0x0000)
struct WBP_NumberOnlyInputTextBlock_C_GetText final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetInputText_Text;                        // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_NumberOnlyInputTextBlock_C_GetText;

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct WBP_NumberOnlyInputTextBlock_C_BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	ETextCommit                                   CommitMethod;                                      // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_NumberOnlyInputTextBlock_C_BndEvt__WBP_NumberOnlyInputTextBlock_WBP_NavInputTextBlock_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature;

// Function WBP_NumberOnlyInputTextBlock.WBP_NumberOnlyInputTextBlock_C.AddNumber
// 0x0004 (0x0004 - 0x0000)
struct WBP_NumberOnlyInputTextBlock_C_AddNumber final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_NumberOnlyInputTextBlock_C_AddNumber;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
