#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingVoiceOuputDevice

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_SettingVoiceOuputDevice.WBP_SettingVoiceOuputDevice_C.Get_ConfigItem_Text_1_Text_0
// 0x0010 (0x0010 - 0x0000)
struct WBP_SettingVoiceOuputDevice_C_Get_ConfigItem_Text_1_Text_0 final
{
public:
	class FText                                   ReturnText;                                        // 0x0000(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_WBP_SettingVoiceOuputDevice_C_Get_ConfigItem_Text_1_Text_0;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
