#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReportTypeButton

#include "Basic.hpp"

#include "UINavigation_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ReportTypeButton.WBP_ReportTypeButton_C
// 0x0040 (0x0950 - 0x0910)
class UWBP_ReportTypeButton_C final : public UUINavComponent
{
public:
	uint8                                         Pad_910[0x8];                                      // 0x0910(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CompressTextBlock_C*               WBP_CompressTextBlock;                             // 0x0918(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_103;                                        // 0x0920(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x0928(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_92C[0x4];                                      // 0x092C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UWBP_ReportTypeButton_C* SelfObject)> OnPushButton;          // 0x0930(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UWidget*                                UnderContent;                                      // 0x0940(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class UWidget*                                TopContent;                                        // 0x0948(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void SelectStateUpdate(bool State);
	void PreConstruct(bool IsDesignTime_PreConstruct);
	class UWidget* DoCustomNavigationTop(EUINavigation Navigation);
	class UWidget* DoCustomNavigation(EUINavigation Navigation);
	void Construct();
	void BndEvt__WBP_ReportTypeButton_NavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ReportTypeButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ReportTypeButton_C")
	}
	static class UWBP_ReportTypeButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ReportTypeButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ReportTypeButton_C;

SDK_NAMESPACE_END
