#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReportTypeButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ReportTypeButton.WBP_ReportTypeButton_C.SelectStateUpdate
// 0x0001 (0x0001 - 0x0000)
struct WBP_ReportTypeButton_C_SelectStateUpdate final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ReportTypeButton_C_SelectStateUpdate;

// Function WBP_ReportTypeButton.WBP_ReportTypeButton_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_ReportTypeButton_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ReportTypeButton_C_PreConstruct;

// Function WBP_ReportTypeButton.WBP_ReportTypeButton_C.DoCustomNavigation
// 0x0010 (0x0010 - 0x0000)
struct WBP_ReportTypeButton_C_DoCustomNavigation final
{
public:
	EUINavigation                                 Navigation;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ReportTypeButton_C_DoCustomNavigation;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
