#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PerformaiceMode

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_PerformaiceMode.WBP_PerformaiceMode_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_PerformaiceMode_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PerformaiceMode_C_PreConstruct;

// Function WBP_PerformaiceMode.WBP_PerformaiceMode_C.BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_PerformaiceMode_C_BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_PerformaiceMode_C_BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
