#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ToggleOption

#include "Basic.hpp"

#include "WBP_ToggleOption_classes.hpp"
#include "WBP_ToggleOption_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ToggleOption.WBP_ToggleOption_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ToggleOption_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ToggleOption_C", "PreConstruct");

	Params::WBP_ToggleOption_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ToggleOption.WBP_ToggleOption_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ToggleOption_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ToggleOption_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ToggleOption.WBP_ToggleOption_C.BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ToggleOption_C::BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature(bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ToggleOption_C", "BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature");

	Params::WBP_ToggleOption_C_BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ToggleOption.WBP_ToggleOption_C.ApplySetting
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ToggleOption_C::ApplySetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ToggleOption_C", "ApplySetting");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
