#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UpOrDownButton

#include "Basic.hpp"

#include "UINavigation_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UpOrDownButton.WBP_UpOrDownButton_C
// 0x0040 (0x0950 - 0x0910)
class UWBP_UpOrDownButton_C final : public UUINavComponent
{
public:
	uint8                                         Pad_910[0x8];                                      // 0x0910(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UTextBlock*                             TextBlock_41;                                      // 0x0918(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsPlus;                                            // 0x0920(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_921[0x3];                                      // 0x0921(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FontSize;                                          // 0x0924(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   PlusText;                                          // 0x0928(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	class FText                                   MinusText;                                         // 0x0938(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void UpdateVisual();
	void PreConstruct(bool IsDesignTime_PreConstruct);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UpOrDownButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UpOrDownButton_C")
	}
	static class UWBP_UpOrDownButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UpOrDownButton_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UpOrDownButton_C;

SDK_NAMESPACE_END
