#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ControllerGradientSlider

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.UpdateSliderBar
// 0x0010 (0x0010 - 0x0000)
struct WBP_ControllerGradientSlider_C_UpdateSliderBar final
{
public:
	double                                        NormalizeValue;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetValue_InValue_ImplicitCast;            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_UpdateSliderBar;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetSliderValue
// 0x0010 (0x0010 - 0x0000)
struct WBP_ControllerGradientSlider_C_SetSliderValue final
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UpdateCall;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_SetSliderValue;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetSelectState
// 0x0001 (0x0001 - 0x0000)
struct WBP_ControllerGradientSlider_C_SetSelectState final
{
public:
	bool                                          IsSelect;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_SetSelectState;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.SetBarColor
// 0x0010 (0x0010 - 0x0000)
struct WBP_ControllerGradientSlider_C_SetBarColor final
{
public:
	struct FLinearColor                           Value;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_SetBarColor;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_ControllerGradientSlider_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_PreConstruct;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.BndEvt__WBP_ControllerGradientSlider_Slider_73_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_ControllerGradientSlider_C_BndEvt__WBP_ControllerGradientSlider_Slider_73_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_BndEvt__WBP_ControllerGradientSlider_Slider_73_K2Node_ComponentBoundEvent_0_OnFloatValueChangedEvent__DelegateSignature;

// Function WBP_ControllerGradientSlider.WBP_ControllerGradientSlider_C.AddSliderValue
// 0x0008 (0x0008 - 0x0000)
struct WBP_ControllerGradientSlider_C_AddSliderValue final
{
public:
	double                                        Value;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ControllerGradientSlider_C_AddSliderValue;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
