#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapContentsWithRandom

#include "Basic.hpp"

#include "ST_cLeonMapData_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_MapContentsWithRandom.WBP_MapContentsWithRandom_C.SelectUpdate
// 0x0001 (0x0001 - 0x0000)
struct WBP_MapContentsWithRandom_C_SelectUpdate final
{
public:
	bool                                          State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapContentsWithRandom_C_SelectUpdate;

// Function WBP_MapContentsWithRandom.WBP_MapContentsWithRandom_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MapContentsWithRandom_C_PreConstruct final
{
public:
	bool                                          IsDesignTime_PreConstruct;                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapContentsWithRandom_C_PreConstruct;

// Function WBP_MapContentsWithRandom.WBP_MapContentsWithRandom_C.BndEvt__WBP_MapContentsWithRandom_WBP_RandomToggle_K2Node_ComponentBoundEvent_0_UpdateRandomState__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_MapContentsWithRandom_C_BndEvt__WBP_MapContentsWithRandom_WBP_RandomToggle_K2Node_ComponentBoundEvent_0_UpdateRandomState__DelegateSignature final
{
public:
	bool                                          NewState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapContentsWithRandom_C_BndEvt__WBP_MapContentsWithRandom_WBP_RandomToggle_K2Node_ComponentBoundEvent_0_UpdateRandomState__DelegateSignature;

// Function WBP_MapContentsWithRandom.WBP_MapContentsWithRandom_C.BndEvt__WBP_MapContentsWithRandom_WBP_MapContents_K2Node_ComponentBoundEvent_1_SelectMap__DelegateSignature
// 0x0030 (0x0030 - 0x0000)
struct WBP_MapContentsWithRandom_C_BndEvt__WBP_MapContentsWithRandom_WBP_MapContents_K2Node_ComponentBoundEvent_1_SelectMap__DelegateSignature final
{
public:
	class UWBP_MapContents_C*                     SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FST_cLeonMapData                       Mapdata;                                           // 0x0008(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MapContentsWithRandom_C_BndEvt__WBP_MapContentsWithRandom_WBP_MapContents_K2Node_ComponentBoundEvent_1_SelectMap__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
