#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingVoiceOuputDevice

#include "Basic.hpp"

#include "WBP_SettingVoiceOuputDevice_classes.hpp"
#include "WBP_SettingVoiceOuputDevice_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_SettingVoiceOuputDevice.WBP_SettingVoiceOuputDevice_C.Get_ConfigItem_Text_1_Text_0
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)

void UWBP_SettingVoiceOuputDevice_C::Get_ConfigItem_Text_1_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingVoiceOuputDevice_C", "Get_ConfigItem_Text_1_Text_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SettingVoiceOuputDevice.WBP_SettingVoiceOuputDevice_C.ApplySetting
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_SettingVoiceOuputDevice_C::ApplySetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SettingVoiceOuputDevice_C", "ApplySetting");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
