#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_cLeonGameSettings

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "ST_cLeonMapData_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.SelectMapMain
// 0x0030 (0x0030 - 0x0000)
struct WBP_cLeonGameSettings_C_SelectMapMain final
{
public:
	class UWBP_MapContentsWithRandom_C*           SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FST_cLeonMapData                       MapData;                                           // 0x0008(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_SelectMapMain;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.SelectMap
// 0x0030 (0x0030 - 0x0000)
struct WBP_cLeonGameSettings_C_SelectMap final
{
public:
	class UWBP_MapContentsWithRandom_C*           SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FST_cLeonMapData                       MapData;                                           // 0x0008(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_SelectMap;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.RandomStructUpdate
// 0x00B8 (0x00B8 - 0x0000)
struct WBP_cLeonGameSettings_C_RandomStructUpdate final
{
public:
	struct FST_cLeonMapData                       StructRef;                                         // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          RandomState;                                       // 0x0028(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_cLeonMapData                       ReturnItem;                                        // 0x0030(0x0028)(Parm, OutParm, HasGetValueTypeHash)
	TArray<class FName>                           Tags;                                              // 0x0058(0x0010)(Edit, BlueprintVisible)
	class FName                                   Temp_name_Variable;                                // 0x0068(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_SelectName_ReturnValue;                   // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_1;                              // 0x0078(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FST_cLeonMapData                       K2Node_SetFieldsInStruct_StructOut;                // 0x0088(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue_1;           // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_RandomStructUpdate;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.RandomStateChange
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_RandomStateChange final
{
public:
	class UWBP_MapContentsWithRandom_C*           SelfWidget;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          RandomState;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_RandomStateChange;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.GetInitialFocusComponent
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_GetInitialFocusComponent final
{
public:
	class UUINavComponent*                        ReturnValue_GetInitialFocusComponent;              // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUINavComponent*                        CallFunc_GetInitialFocusComponent_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_GetInitialFocusComponent;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.DoCustomNavigation
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_DoCustomNavigation final
{
public:
	EUINavigation                                 Navigation;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_DoCustomNavigation;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_LimitBullet_K2Node_ComponentBoundEvent_30_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_LimitBullet_K2Node_ComponentBoundEvent_30_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_LimitBullet_K2Node_ComponentBoundEvent_30_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterWait_K2Node_ComponentBoundEvent_23_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterWait_K2Node_ComponentBoundEvent_23_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterWait_K2Node_ComponentBoundEvent_23_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterNum_K2Node_ComponentBoundEvent_22_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterNum_K2Node_ComponentBoundEvent_22_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_HunterNum_K2Node_ComponentBoundEvent_22_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_GameTime_K2Node_ComponentBoundEvent_27_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_GameTime_K2Node_ComponentBoundEvent_27_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_GameTime_K2Node_ComponentBoundEvent_27_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ForceProvocationTime_K2Node_ComponentBoundEvent_29_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ForceProvocationTime_K2Node_ComponentBoundEvent_29_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ForceProvocationTime_K2Node_ComponentBoundEvent_29_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenSearch_K2Node_ComponentBoundEvent_25_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenSearch_K2Node_ComponentBoundEvent_25_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenSearch_K2Node_ComponentBoundEvent_25_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenLook_K2Node_ComponentBoundEvent_24_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenLook_K2Node_ComponentBoundEvent_24_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenLook_K2Node_ComponentBoundEvent_24_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenAnswer_K2Node_ComponentBoundEvent_26_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenAnswer_K2Node_ComponentBoundEvent_26_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_ChickenAnswer_K2Node_ComponentBoundEvent_26_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_CheckAnswersTime_K2Node_ComponentBoundEvent_28_TextChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_CheckAnswersTime_K2Node_ComponentBoundEvent_28_TextChanged__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_NumberOnlyInputTextBlock_CheckAnswersTime_K2Node_ComponentBoundEvent_28_TextChanged__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMosaic_K2Node_ComponentBoundEvent_18_ChangeValue__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMosaic_K2Node_ComponentBoundEvent_18_ChangeValue__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMosaic_K2Node_ComponentBoundEvent_18_ChangeValue__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMonochrome_K2Node_ComponentBoundEvent_19_ChangeValue__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMonochrome_K2Node_ComponentBoundEvent_19_ChangeValue__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterMonochrome_K2Node_ComponentBoundEvent_19_ChangeValue__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterHorror_K2Node_ComponentBoundEvent_20_ChangeValue__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterHorror_K2Node_ComponentBoundEvent_20_ChangeValue__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_WBP_BoolSwitcher_FilterHorror_K2Node_ComponentBoundEvent_20_ChangeValue__DelegateSignature;

// Function WBP_cLeonGameSettings.WBP_cLeonGameSettings_C.BndEvt__WBP_cLeonGameSettings_MiniBody_K2Node_ComponentBoundEvent_0_ChangeValue__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_MiniBody_K2Node_ComponentBoundEvent_0_ChangeValue__DelegateSignature final
{
public:
	bool                                          Value;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_cLeonGameSettings_C_BndEvt__WBP_cLeonGameSettings_MiniBody_K2Node_ComponentBoundEvent_0_ChangeValue__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
