#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UpOrDownButton

#include "Basic.hpp"

#include "WBP_UpOrDownButton_classes.hpp"
#include "WBP_UpOrDownButton_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UpOrDownButton.WBP_UpOrDownButton_C.UpdateVisual
// (BlueprintCallable, BlueprintEvent)

void UWBP_UpOrDownButton_C::UpdateVisual()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UpOrDownButton_C", "UpdateVisual");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UpOrDownButton.WBP_UpOrDownButton_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime_PreConstruct                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UpOrDownButton_C::PreConstruct(bool IsDesignTime_PreConstruct)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UpOrDownButton_C", "PreConstruct");

	Params::WBP_UpOrDownButton_C_PreConstruct Parms{};

	Parms.IsDesignTime_PreConstruct = IsDesignTime_PreConstruct;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
