#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoiceChatControlPanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_VoiceChatControlPanel.WBP_VoiceChatControlPanel_C
// 0x0050 (0x0390 - 0x0340)
class UWBP_VoiceChatControlPanel_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_SettingVoiceOuputDevice_C*         WBP_SettingVoiceOuputDevice;                       // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SettingVoiceInputDevice_C*         WBP_SettingVoiceInputDevice;                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_52;                                      // 0x0358(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongTapButton_OnAnimation_C*           LongTapButton_OnAnimation;                         // 0x0360(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<struct FUniqueNetIdRepl>               BoxTarget;                                         // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UWBP_VoiceChatUserSettings_C*           PreContent;                                        // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWBP_VoiceChatUserSettings_C*>   UserSettings;                                      // 0x0380(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void PreConstruct(bool IsDesignTime_PreConstruct);
	void GetSortedCharacters(TArray<class ABP_FirstPersonPlayerState_Online_C*>* OutActors);
	void GetRootFocusTarget(class UWidget** Widget);
	void Construct();
	void BndEvt__WBP_VoiceChatControlPanel_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_VoiceChatControlPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_VoiceChatControlPanel_C")
	}
	static class UWBP_VoiceChatControlPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_VoiceChatControlPanel_C>();
	}
};
DUMPER7_ASSERTS_UWBP_VoiceChatControlPanel_C;

SDK_NAMESPACE_END
