#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ToggleOption

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_ToggleOption.WBP_ToggleOption_C
// 0x0060 (0x03A0 - 0x0340)
class UWBP_ToggleOption_C final : public UUserWidget
{
public:
	uint8                                         Pad_340[0x8];                                      // 0x0340(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_BoolSwitcher_C*                    WBP_BoolSwitcher;                                  // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             configItem_text;                                   // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<int32>                                 FlameRateArray_0;                                  // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void()>              UpdateSettings;                                    // 0x0368(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UBP_ConfigSaveGame_C*                   As_BP_Config_Save_Game;                            // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x0380(0x0010)(Edit, BlueprintVisible)
	int32                                         TextIndex;                                         // 0x0390(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   TargetName;                                        // 0x0394(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime_PreConstruct);
	void Construct();
	void BndEvt__WBP_PerformaiceMode_WBP_BoolSwitcher_K2Node_ComponentBoundEvent_2_ChangeValue__DelegateSignature(bool Value);
	void ApplySetting();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_ToggleOption_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_ToggleOption_C")
	}
	static class UWBP_ToggleOption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ToggleOption_C>();
	}
};
DUMPER7_ASSERTS_UWBP_ToggleOption_C;

SDK_NAMESPACE_END
